### ISSUE TITLE
local db failing to initialize

### ISSUE THREAD

**Issue by janto** [dthyresson/redwoodblog-rbac#6]
The creation of a sqlite db (as in `.env.defaults`) for local dev does not seem to work. Looks like it has to be postgres.

I change the entry to `DATABASE_URL=postgres://<username>:<password>@localhost/the_db`
and also had to run `yarn prisma db push --preview-feature --schema=api/db/schema.prisma` (as per https://github.com/prisma/prisma/issues/4571#issuecomment-754650296) to get it working.
Could the readme and env files please be changed so others don't also spend time on this?

Looking forward to using redwood! Looks nice.

**Comment by dthyresson** [comment]
Hi @janto I actually never thought about local dev using SQLite since this app relies on it being deployed to Netlify and SQLite isn't often an option and so I typically develop using postgres and well as deploy.

Hence the `schema` file has postgres set:

https://github.com/dthyresson/redwoodblog-rbac/blob/b9e962510a51524e1f85114f35366d1ae409b1ae/api/db/schema.prisma#L7

But I'll definitely make that change and comment so it's more clear. Thanks!

> also had to run yarn prisma db push --preview-feature --schema=api/db/schema.prisma (as per prisma/prisma#4571 (comment)) to get it working.

Ok, good to know. I thoguht a traditional `yarn rw prisma migrate dev` would be ok and the the normal `yarn rw deploy netlify` would handle that when pointing to your prod postgres db.

**Comment by dthyresson** [comment]
Have added docs. Thanks for the feedback and hope this clarifies for others. Cheers.
